// Generated by Selenium IDE
package junitpkg;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class T2Test {
  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
//    js = (JavascriptExecutor) driver;
//    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void t2() {
    driver.get("https://www.google.com/");
    driver.findElement(By.id("APjFqb")).sendKeys("books");
    driver.findElement(By.cssSelector("form > div:nth-child(1)")).click();
    driver.findElement(By.cssSelector("center:nth-child(1) > .gNO89b")).click();
    driver.close();
  }
}
